language: python
python:
#  - "3.3"
  - "2.7"
#  - "2.6"
install: pip install -r requirements_dev.txt
# command to run tests, e.g. python setup.py test
script: drf_to_s3/runtests/runtests.py
env:
  global:
    secure: N+bw+xdt1r9p9ePkNoUkTluhT2T7TZeN/NletFPUps/bubO8o0tAifLPwqHSoBIh4N4ms4heNHf/nH7lV+8V5VQVaU/rdTfKc8CJW3OB7wmt/ZDU9Gry8RYFvxvfWCib0WHBxh9tvGacJ+t+Yd5eevpRTYZHS4OoGmmRi098PNE=
